services:
  database:
    container_name: postgres_db_personas
    image: postgres:latest
    environment:
      - POSTGRES_DB=persona
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
    ports:
      - '5433:5432'
  backend:
    container_name: app_api_personas
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '5000:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5433/persona
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin123
    depends_on:
      - database
  frontend:
    container_name: app_web_personas
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '60:80'
    depends_on:
      - backend
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/clientes-app:/usr/share/nginx/html
    ports:
      - '82:80'